version: "3.8"

volumes:
  ams_db:


services:
  ams-database:
    image: postgres:14.4-alpine
    restart: unless-stopped
    container_name: db.ams.com
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      retries: 3
    ports:
      - "5439:5432"
    volumes:
      - ams_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ams
      POSTGRES_USER: amsadmin
      POSTGRES_PASSWORD: ams123

  ams-api:
    build:
      context: .
      dockerfile: JRE.Dockerfile
    container_name: api.ams.com
    ports:
      - "6654:8080"
    volumes:
      - /opt/resources/files:/opt/resources/files
    environment:
      SPRING_PROFILES_ACTIVE: default,prod
