spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/ams
    username: amsadmin
    password: ams123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

files:
  storage:
    path: src/main/resources/images

server:
  port: 6654
  name: http://localhost:8080

logging:
  file:
    name: ${LOG_FILE:ams-kshrd.log}
