spring:
  application:
    name: ams-application
  datasource:
    url: jdbc:postgresql://localhost:5439/ams
    username: amsadmin
    password: ams123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    active: default

files:
  storage:
    path: src/main/resources/images

server:
  name: http://localhost:8080
