spring:
  application:
    name: ams-application
  datasource:
    url: jdbc:postgresql://db.ams.com:5432/ams
    username: amsadmin
    password: ams123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

files:
  storage:
    path: /opt/resources/files

server:
  name: https://springams.hrd-edu.info