spring:
  application:
    name: ams-application
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
  profiles:
    active: default,dev

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
