spring:
  datasource:
    url: jdbc:postgresql://db.ams.com:5432/ams
    username: amsadmin
    password: ams123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

files:
  storage:
    path: /opt/resources/files

server:
  name: https://springams.hrd-edu.info

logging:
  file:
    name: ${LOG_FILE:/opt/ams-kshrd.log}
